Release v4.2.3
qld-gov-au/qg-web-template pull request #1045
Opened 2023-08-01 22:37 UTC by ghazal-salehi

Merging 4.2.3 to master to prepare for Prod release on 17/8.

2023-08-01 22:50 UTC, ThrawnCA requested changes
Build is broken.

2023-08-01 23:02 UTC, ghazal-salehi commented
I'll look into the test file shortly

2023-08-01 23:05 UTC, ghazal-salehi commented
Squiz updated on their side and the results are different now. I'll update them.

2023-08-02 00:17 UTC, ThrawnCA approved these changes

2023-08-03 03:51 UTC, duttonw approved these changes

2023-08-03 04:10 UTC, merged