Resolving lint errors
qld-gov-au/qg-web-template pull request #1347
Opened 2023-11-30 01:01 UTC by ghazal-salehi

`npm i eslint`
`npx eslint --fix src`

2023-11-30 02:14 UTC, ThrawnCA commented on src/assets/_project/_blocks/components/forms/qg-address-autocomplete.js
> +      if (getParameterVal !== false) {
"if not...else" is a double negative, consider swapping it around.

2023-11-30 02:15 UTC, ThrawnCA commented on src/assets/_project/_blocks/components/forms/qg-address-autocomplete.js
> +      if (getParameterVal !== false) {
"if not...else" is a double negative, consider swapping it around.

2023-11-30 02:24 UTC, ThrawnCA commented on src/assets/_project/lib/ext/butterfly/jquery.butterfly.js
I don't think we should be linting library modules.

2023-11-30 02:25 UTC, ThrawnCA requested changes

2023-11-30 02:25 UTC, ThrawnCA commented on src/docs/assets/js/prism.js
Don't lint minified files. Adding spaces defeats the purpose of minification.

2023-11-30 08:11 UTC, ghazal-salehi commented on src/assets/_project/lib/ext/butterfly/jquery.butterfly.js
When I tried running `npm run publish-test-npm` locally, lint errors stopped building remotely. `npm run build` finishes locally though (still showing the errors). Can you try `npm run publish-test-npm` locally on develop branch to see if that works for you? If it does we can leave some of the lint errors like the ones in the minified js and external libraries.

I checked older versions of eslint package as well. Still shows 700 errors on dev branch. Not sure why all of a sudden these started happening.

2023-11-30 22:40 UTC, ghazal-salehi commented on src/docs/assets/js/prism.js
There are more ext libraries. I will revert them.

2023-11-30 23:42 UTC, duttonw commented on src/assets/_project/_blocks/components/accordion/qg-accordion.js
> +    const self = this;
don't think these can be const. Is this code stood up multiple times for each accordion?

2023-11-30 23:42 UTC, duttonw commented on src/assets/_project/_blocks/components/carousel/qg-carousel.js
> +  const carousels = [];
can't be const, we need to be adding items to the array.

2023-11-30 23:44 UTC, duttonw requested changes
Const is only used if it will never change.

There is too many places where  ```let``` is the only choice.  (unless this javascript function code is creation immutable objects instead of being 'function' calls.

https://www.freecodecamp.org/news/differences-between-var-let-const-javascript/#:~:text=If%20you%20never%20want%20a,is%20the%20keyword%20for%20you

2023-11-30 23:44 UTC, duttonw commented on src/docs/assets/js/prism.js
ext libraries should be ignored from lint checkers. same as the dist folder etc.

2023-12-01 01:44 UTC, ghazal-salehi commented
Should now be good to review again. Sorry about too many commits!

2023-12-01 01:51 UTC, ghazal-salehi commented
> Const is only used if it will never change.
> 
> There is too many places where `let` is the only choice. (unless this javascript function code is creation immutable objects instead of being 'function' calls.
> 
> https://www.freecodecamp.org/news/differences-between-var-let-const-javascript/#:~:text=If%20you%20never%20want%20a,is%20the%20keyword%20for%20you

I updated some references in accordion.js and carousel.js to use `var` instead of `let` to pass lint check.
npx eslint --fix seems to be not so reliable after all.

> Const is only used if it will never change.
> 
> There is too many places where `let` is the only choice. (unless this javascript function code is creation immutable objects instead of being 'function' calls.
> 
> https://www.freecodecamp.org/news/differences-between-var-let-const-javascript/#:~:text=If%20you%20never%20want%20a,is%20the%20keyword%20for%20you

2023-12-01 04:48 UTC, ThrawnCA approved these changes

2023-12-01 05:19 UTC, merged