Qoldev 343 remove underline from alert danger
qld-gov-au/qg-web-template pull request #868
Opened 2023-04-05 04:23 UTC by ghazal-salehi

https://ssq-qol.atlassian.net/browse/QOLDEV-343

https://oss-uat.clients.squiz.net/contact-us

When youo submit contact us form without the required fields:
![image](https://user-images.githubusercontent.com/126438691/229980380-d05ab956-dd6e-4b2f-aa01-b35c47cedce0.png)

Form io also needs to be updated to remove role='link' from the span. Otherwise the underline will be still there.

2023-04-05 23:28 UTC, ThrawnCA requested changes

2023-04-05 23:28 UTC, ThrawnCA commented on src/assets/_project/_blocks/components/link/_qg-link.scss
> -    &:not(span[role=link] *) {
This is needed on the Contact Us page. Why was it removed?

2023-04-05 23:29 UTC, ThrawnCA approved these changes

2023-04-06 01:29 UTC, ghazal-salehi commented
After further discussion with the design team, we decided to keep the underlines. It appears that the comments 'behave' like anchors. Because when you click on the them it will take the user to the causing field using data-component-key values. I'll revert most of the changes made in this PR. And will only increase the text-underline-offset to 5px.

2023-04-06 05:24 UTC, ghazal-salehi commented
Bec advised to put this ticket back to backlog until we improve font and font-size overall. I think that would cascade and fix this issue. I'll close this PR and will have a separate one for the logo.

2023-04-17 23:55 UTC, ghazal-salehi commented
The pull request was accidentally closed. It will update the underline offset to the links inside the alertbox.

2023-04-19 01:52 UTC, ThrawnCA approved these changes

2023-04-19 02:01 UTC, merged