Qoldev 44 services blurb text color
qld-gov-au/qg-web-template pull request #939
Opened 2023-05-10 23:16 UTC by ghazal-salehi

2023-05-11 04:36 UTC, stvp-qld commented
Hey @ghazal-salehi, 

Can you quickly check this behaviour on other buttons - further down this page a blue button now uses black text which makes it harder to read.  It might not have been intended?   

![image](https://github.com/qld-gov-au/qg-web-template/assets/126438309/34603c88-0acc-44a8-9b8e-d4669046626e)

2023-05-11 05:34 UTC, ghazal-salehi commented
> Hey @ghazal-salehi,
> 
> Can you quickly check this behaviour on other buttons - further down this page a blue button now uses black text which makes it harder to read. It might not have been intended?
> 
> UAT vs PROD
> 
> ![image](https://user-images.githubusercontent.com/126438309/237574387-34603c88-0acc-44a8-9b8e-d4669046626e.png)

That is right. However this pull request targets the buttons within blurb. This issue related to buttons inside cards. I'll see if I can do a quick fix.

2023-05-11 07:06 UTC, ghazal-salehi commented
It is now updated to fix btn-secondary.

2023-05-11 23:02 UTC, ThrawnCA requested changes
Build is failing.

2023-05-14 23:08 UTC, ThrawnCA approved these changes

2023-05-14 23:21 UTC, merged